version: '3.8'

services:
  adonis:
    build:
      context: .
    container_name: adonis-app
    ports:
      - "3333:3333" 
    environment:
      - DB_CONNECTION=pg
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=demoproject
    volumes:
      - .:/app
    depends_on:
      - db 
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demoproject
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
